from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


@dataclass(frozen=True)
class GeneratedReport:
    filename: str
    filepath: Path


class ComplianceReportGenerator:
    """Builds a persisted PDF report for a completed compliance analysis."""

    def __init__(self, storage_dir: Path) -> None:
        self.storage_dir = storage_dir
        self.storage_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        *,
        project_id: int,
        project_name: str,
        analysis_result: dict[str, Any],
        compliance_score: int,
        deviations: list[dict[str, Any]],
        recommendations: list[str],
        specification_filename: str,
        vendor_filename: str,
        timestamp: datetime,
    ) -> GeneratedReport:
        """Generate the PDF report and return its saved file metadata."""

        filename = f"report_{project_id}_{timestamp.strftime('%Y_%m_%d_%H%M%S')}.pdf"
        filepath = self.storage_dir / filename
        styles = self._styles()
        doc = SimpleDocTemplate(
            str(filepath),
            pagesize=A4,
            rightMargin=0.55 * inch,
            leftMargin=0.55 * inch,
            topMargin=0.65 * inch,
            bottomMargin=0.65 * inch,
            title="Compliance Analysis Report",
        )

        summary = analysis_result.get("summary", {})
        severity_counts = self._severity_counts(deviations)
        story: list[Any] = [
            Spacer(1, 1.5 * inch),
            Paragraph("AI EPC Orbit", styles["CoverBrand"]),
            Paragraph("Compliance Analysis Report", styles["CoverTitle"]),
            Spacer(1, 0.35 * inch),
            Paragraph(project_name, styles["CenterText"]),
            Paragraph(timestamp.strftime("%d %b %Y, %H:%M"), styles["CenterText"]),
            Spacer(1, 0.2 * inch),
            Paragraph("Generated by AI", styles["CenterText"]),
            PageBreak(),
            Paragraph("Executive Summary", styles["Heading1"]),
            self._summary_table(
                [
                    ("Compliance Score", f"{compliance_score}%"),
                    ("Total Clauses", str(summary.get("total_clauses", max(len(deviations), 1)))),
                    ("Matched Clauses", str(summary.get("matched_clauses", max(0, 10 - len(deviations))))),
                    ("Deviations", str(len(deviations))),
                    ("Critical Issues", str(severity_counts["critical"])),
                    ("High Issues", str(severity_counts["high"])),
                    ("Medium Issues", str(severity_counts["medium"])),
                    ("Low Issues", str(severity_counts["low"])),
                    ("Specification", specification_filename),
                    ("Vendor Submitted", vendor_filename),
                ],
                styles,
            ),
            Spacer(1, 0.25 * inch),
            Paragraph("Compliance Gauge", styles["Heading1"]),
            Paragraph("Compliance Score", styles["CenterText"]),
            Paragraph(f"{compliance_score}%", styles["Gauge"]),
            Spacer(1, 0.25 * inch),
            Paragraph("Deviation Register", styles["Heading1"]),
            self._deviation_table(deviations, styles),
            Spacer(1, 0.25 * inch),
            Paragraph("AI Recommendations", styles["Heading1"]),
            *[Paragraph(f"- {item}", styles["Body"]) for item in recommendations],
            Spacer(1, 0.25 * inch),
            Paragraph("Risk Summary", styles["Heading1"]),
            self._risk_table(deviations, styles),
        ]

        doc.build(story, onFirstPage=self._footer, onLaterPages=self._footer)
        return GeneratedReport(filename=filename, filepath=filepath)

    def _styles(self) -> dict[str, ParagraphStyle]:
        base = getSampleStyleSheet()
        return {
            "CoverBrand": ParagraphStyle(
                "CoverBrand",
                parent=base["Title"],
                fontName="Helvetica-Bold",
                fontSize=28,
                leading=34,
                textColor=colors.HexColor("#12355b"),
                alignment=TA_CENTER,
            ),
            "CoverTitle": ParagraphStyle(
                "CoverTitle",
                parent=base["Title"],
                fontSize=20,
                leading=26,
                textColor=colors.HexColor("#1f766f"),
                alignment=TA_CENTER,
            ),
            "Heading1": ParagraphStyle(
                "Heading1",
                parent=base["Heading1"],
                fontSize=15,
                leading=19,
                textColor=colors.HexColor("#12355b"),
                spaceAfter=8,
            ),
            "Body": ParagraphStyle("Body", parent=base["BodyText"], fontSize=8.5, leading=11),
            "Small": ParagraphStyle("Small", parent=base["BodyText"], fontSize=7, leading=9),
            "CenterText": ParagraphStyle(
                "CenterText",
                parent=base["BodyText"],
                fontSize=11,
                leading=16,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#4b6075"),
            ),
            "Gauge": ParagraphStyle(
                "Gauge",
                parent=base["Title"],
                fontSize=42,
                leading=48,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#1f766f"),
            ),
        }

    def _summary_table(self, rows: list[tuple[str, str]], styles: dict[str, ParagraphStyle]) -> Table:
        table = Table(
            [[Paragraph(label, styles["Body"]), Paragraph(value, styles["Body"])] for label, value in rows],
            colWidths=[2.0 * inch, 4.3 * inch],
        )
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#edf7f6")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d5e3e8")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        return table

    def _deviation_table(self, deviations: list[dict[str, Any]], styles: dict[str, ParagraphStyle]) -> Table:
        headers = ["Clause", "Specification", "Vendor Submitted", "Status", "Severity", "Impact", "Recommendation", "Source"]
        rows = [headers]
        for item in deviations[:25]:
            rows.append(
                [
                    item.get("clause", ""),
                    item.get("required_value") or item.get("requirement", ""),
                    item.get("submitted_value", ""),
                    item.get("status", ""),
                    item.get("severity", ""),
                    item.get("impact", ""),
                    item.get("recommendation", ""),
                    f"{item.get('source', '')} p.{item.get('page', '')}".strip(),
                ]
            )
        if len(rows) == 1:
            rows.append(["-", "No deviations found", "-", "Compliant", "Low", "-", "-", "-"])

        table = Table(
            [[Paragraph(str(cell), styles["Small"]) for cell in row] for row in rows],
            repeatRows=1,
            colWidths=[0.62 * inch, 0.9 * inch, 0.85 * inch, 0.55 * inch, 0.58 * inch, 0.95 * inch, 1.15 * inch, 0.7 * inch],
        )
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#12355b")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#d5e3e8")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("PADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        return table

    def _risk_table(self, deviations: list[dict[str, Any]], styles: dict[str, ParagraphStyle]) -> Table:
        critical = [item for item in deviations if item.get("severity") == "Critical"]
        high = [item for item in deviations if item.get("severity") in ("High", "Major")]
        business_impact = "Critical vendor deviations can delay procurement release, commissioning readiness, and milestone acceptance."
        actions = "Resolve critical and high deviations before release; assign owners; request revised vendor submittals."
        return self._summary_table(
            [
                ("Critical Risks", str(len(critical))),
                ("High Risks", str(len(high))),
                ("Business Impact", business_impact),
                ("Recommended Actions", actions),
            ],
            styles,
        )

    def _severity_counts(self, deviations: list[dict[str, Any]]) -> dict[str, int]:
        return {
            "critical": sum(1 for item in deviations if item.get("severity") == "Critical"),
            "high": sum(1 for item in deviations if item.get("severity") in ("High", "Major")),
            "medium": sum(1 for item in deviations if item.get("severity") == "Medium"),
            "low": sum(1 for item in deviations if item.get("severity") == "Low"),
        }

    def _footer(self, canvas, doc) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#6d7f8f"))
        canvas.drawCentredString(A4[0] / 2, 0.35 * inch, "Generated by EPC Orbit AI")
        canvas.restoreState()
